# Generated by Django 5.1.7 on 2025-04-27 19:16

from django.db import migrations

# Data to insert for SubCategories
INITIAL_SUBCATEGORIES = [
    {'name': 'Вёдра и литьевые контейнера', 'description': 'Вёдра и литьевые контейнера', 'image_url': 'Вёдра и литьевые контейнера', 'category_id': 1},
    {'name': 'Упаковка для фаст-фуда и суши', 'description': 'Упаковка для фаст-фуда и суши', 'image_url': 'Упаковка для фаст-фуда и суши', 'category_id': 1},
    {'name': 'Контейнера прямоугольные и круглые PET', 'description': 'Контейнера прямоугольные и круглые PET', 'image_url': 'Контейнера прямоугольные и круглые PET', 'category_id': 1},
    {'name': 'Контейнера прямоугольные и круглые ПП', 'description': 'Контейнера прямоугольные и круглые ПП', 'image_url': 'Контейнера прямоугольные и круглые ПП', 'category_id': 1},
    {'name': 'Упаковка для тортов', 'description': 'Упаковка для тортов', 'image_url': 'Упаковка для тортов', 'category_id': 1},
    {'name': 'Упаковка для кондитерских изделий РК, РКС, СК', 'description': 'Упаковка для кондитерских изделий РК, РКС, СК', 'image_url': 'Упаковка для кондитерских изделий РК, РКС, СК', 'category_id': 1},
    {'name': 'Упаковка для пирогов', 'description': 'Упаковка для пирогов', 'image_url': 'Упаковка для пирогов', 'category_id': 1},
    {'name': 'Пластиковая упаковка под яйца', 'description': 'Пластиковая упаковка под яйца', 'image_url': 'Пластиковая упаковка под яйца', 'category_id': 1},
    {'name': 'Пакеты бумажные', 'description': 'Пакеты бумажные', 'image_url': 'Пакеты бумажные', 'category_id': 2},
    {'name': 'Картонно-бумажная продукция', 'description': 'Картонно-бумажная продукция', 'image_url': 'Картонно-бумажная продукция', 'category_id': 2},
    {'name': 'Гофро-коробки и коробки из-под пиццы', 'description': 'Гофро-коробки и коробки из-под пиццы', 'image_url': 'Гофро-коробки и коробки из-под пиццы', 'category_id': 2},
    {'name': 'Стаканы пластмасс', 'description': 'Стаканы пластмасс', 'image_url': 'Стаканы пластмасс', 'category_id': 3},
    {'name': 'Стаканы бумажные', 'description': 'Стаканы бумажные', 'image_url': 'Стаканы бумажные', 'category_id': 3},
    {'name': 'Тарелки и миски', 'description': 'Тарелки и миски', 'image_url': 'Тарелки и миски', 'category_id': 3},
    {'name': 'Столовые приборы', 'description': 'Столовые приборы', 'image_url': 'Столовые приборы', 'category_id': 3},
    {'name': 'Вспененные лотки', 'description': 'Вспененные лотки', 'image_url': 'Вспененные лотки', 'category_id': 4},
    {'name': 'Вспененные ланч-боксы', 'description': 'Вспененные ланч-боксы', 'image_url': 'Вспененные ланч-боксы', 'category_id': 4},
    {'name': 'Алюминиевые формы', 'description': 'Алюминиевые формы', 'image_url': 'Алюминиевые формы', 'category_id': 4},
    {'name': 'Алюминиевая фольга', 'description': 'Алюминиевая фольга', 'image_url': 'Алюминиевая фольга', 'category_id': 4},
    {'name': 'Одежда для кондитеров', 'description': 'Одежда для кондитеров', 'image_url': 'Одежда для кондитеров', 'category_id': 5},
    {'name': 'Бумага для выпекания', 'description': 'Бумага для выпекания', 'image_url': 'Бумага для выпекания', 'category_id': 5},
    {'name': 'Подложки и салфетки под торты', 'description': 'Подложки и салфетки под торты', 'image_url': 'Подложки и салфетки под торты', 'category_id': 5},
    {'name': 'Кондитерский инвентарь', 'description': 'Кондитерский инвентарь', 'image_url': 'Кондитерский инвентарь', 'category_id': 5},
    {'name': 'Аксессуары (трубочки, украшения)', 'description': 'Аксессуары (трубочки, украшения)', 'image_url': 'Аксессуары (трубочки, украшения)', 'category_id': 5},
    {'name': 'Пленки PE, POF, ПВХ', 'description': 'Пленки PE, POF, ПВХ', 'image_url': 'Пленки PE, POF, ПВХ', 'category_id': 6},
    {'name': 'Пакеты полиэтиленовые', 'description': 'Пакеты полиэтиленовые', 'image_url': 'Пакеты полиэтиленовые', 'category_id': 6},
    {'name': 'Чистящие средства', 'description': 'Чистящие средства', 'image_url': 'Чистящие средства', 'category_id': 7},
    {'name': 'Кондитерское сырьё', 'description': 'Кондитерское сырьё', 'image_url': 'Кондитерское сырьё', 'category_id': 8},
]

def populate_subcategories(apps, schema_editor):
    """
    Inserts the initial set of subcategories using the historical model state.
    """
    SubCategory = apps.get_model('shop', 'SubCategoryModel') # <<<--- REPLACE 'your_app_name'
    # Category = apps.get_model('your_app_name', 'Category') # Not strictly needed if using category_id
    db_alias = schema_editor.connection.alias

    for subcategory_data in INITIAL_SUBCATEGORIES:
        # When creating objects with foreign keys in data migrations,
        # it's often easiest to provide the ID directly using the '_id' suffix
        # for the ForeignKey field name (e.g., 'category_id' if your field is 'category').
        SubCategory.objects.using(db_alias).create(**subcategory_data)

    # Alternative using bulk_create (potentially faster, check DB compatibility with specified PKs):
    # subcategory_objects = [SubCategory(**data) for data in INITIAL_SUBCATEGORIES]
    # SubCategory.objects.using(db_alias).bulk_create(subcategory_objects)


def unpopulate_subcategories(apps, schema_editor):
    """
    Deletes the subcategories inserted by this migration.
    """
    SubCategory = apps.get_model('shop', 'SubCategoryModel') # <<<--- REPLACE 'your_app_name'
    db_alias = schema_editor.connection.alias

    # Delete based on the IDs we inserted
    subcategory_ids = [sc['id'] for sc in INITIAL_SUBCATEGORIES]
    SubCategory.objects.using(db_alias).filter(id__in=subcategory_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_populate_initial_categories'),
    ]

    operations = [
        migrations.RunPython(populate_subcategories, reverse_code=unpopulate_subcategories),
    ]
