# Generated by Django 5.1.6 on 2025-02-16 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_item_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Sub Category', 'verbose_name_plural': 'Sub Categories'},
        ),
        migrations.AlterModelTable(
            name='subcategory',
            table='sub_categories',
        ),
    ]
