# Generated by Django 5.1.6 on 2025-02-17 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_cart_updated_at_alter_item_lovers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='cart',
            name='empty',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='started_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
