# Generated by Django 5.1.6 on 2025-02-17 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_cart_created_at_remove_cart_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='shop.item'),
        ),
    ]
