# Generated by Django 5.1.6 on 2025-02-17 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_cartitem_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='items', to='shop.cart')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='shop.item')),
            ],
            options={
                'verbose_name': 'CartItem',
                'verbose_name_plural': 'CartItems',
                'db_table': 'cart_items',
            },
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
