# Generated by Django 5.1.6 on 2025-02-17 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_cartitem1_delete_cartitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItem1',
            new_name='CartItem',
        ),
    ]
