# Generated by Django 5.1.6 on 2025-02-17 09:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_cartitem_cart_cartitem_item_cartitem_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='started_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 17, 9, 33, 30, 798749)),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.cart'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.item'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
